### ISSUE TITLE
ARM64 builds

### ISSUE THREAD

**Issue by aidansteele** [bpierre/esbuild-config#8]
Hiya,

I am running MacOS on an M1 CPU, which is the arm64 architecture. I get the following error when I try to install deps that include `esbuild-config`. 

```
% npm ci    
npm ERR! code 1
npm ERR! path /Users/aidan/dev/stedi/state/node_modules/esbuild-config
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Unsupported platform: darwin arm64 LE

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aidan/.npm/_logs/2021-09-27T23_17_30_176Z-debug.log
```

I'm not familiar enough with Rust to submit a potential PR to fix this, sorry!

**Comment by finwo** [comment]
Same thing when running on `linux arm64 LE` (docker on m1 mac)

**Comment by bpierre** [comment]
I published [a new version](https://github.com/bpierre/esbuild-config/releases/tag/v1.0.0) that adds universal binaries for macOS (x68_64 + arm64) and arm64 binaries for Linux.

Let me know if there is any issue!
